name: build

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Neutralino CLI
        run: npm install -g @neutralinojs/neu

      - name: Build widget
        run: |
          neu update
          neu build --embed-resources

      - name: Upload binaries
        uses: actions/upload-artifact@v4
        with:
          name: binaries
          path: ./dist/
